 insert into pais values
 (pais_seq.nextval,'Afeganistão'), 
 (pais_seq.nextval,'África do Sul'), 
 (pais_seq.nextval,'Albânia'), 
 (pais_seq.nextval,'Alemanha'), 
 (pais_seq.nextval,'Andorra'), 
 (pais_seq.nextval,'Angola'), 
 (pais_seq.nextval,'Antiga e Barbuda'), 
 (pais_seq.nextval,'Arábia Saudita'), 
 (pais_seq.nextval,'Argélia'), 
 (pais_seq.nextval,'Argentina'), 
 (pais_seq.nextval,'Arménia'), 
 (pais_seq.nextval,'Austrália'), 
 (pais_seq.nextval,'Áustria'), 
 (pais_seq.nextval,'Azerbaijão'), 
 (pais_seq.nextval,'Bahamas'), 
 (pais_seq.nextval,'Bangladexe'), 
 (pais_seq.nextval,'Barbados'), 
 (pais_seq.nextval,'Barém'), 
 (pais_seq.nextval,'Bélgica'), 
 (pais_seq.nextval,'Belize'), 
 (pais_seq.nextval,'Benim'), 
 (pais_seq.nextval,'Bielorrússia'), 
 (pais_seq.nextval,'Bolívia'), 
 (pais_seq.nextval,'Bósnia e Herzegovina'), 
 (pais_seq.nextval,'Botsuana'), 
 (pais_seq.nextval,'Brasil'), 
 (pais_seq.nextval,'Brunei'), 
 (pais_seq.nextval,'Bulgária'), 
 (pais_seq.nextval,'Burquina Faso'), 
 (pais_seq.nextval,'Burúndi'), 
 (pais_seq.nextval,'Butão'), 
 (pais_seq.nextval,'Cabo Verde'), 
 (pais_seq.nextval,'Camarões'), 
 (pais_seq.nextval,'Camboja'), 
 (pais_seq.nextval,'Canadá'), 
 (pais_seq.nextval,'Catar'), 
 (pais_seq.nextval,'Cazaquistão'), 
 (pais_seq.nextval,'Chade'), 
 (pais_seq.nextval,'Chile'), 
 (pais_seq.nextval,'China'), 
 (pais_seq.nextval,'Chipre'), 
 (pais_seq.nextval,'Colômbia'), 
 (pais_seq.nextval,'Comores'), 
 (pais_seq.nextval,'Congo-Brazzaville'), 
 (pais_seq.nextval,'Coreia do Norte'), 
 (pais_seq.nextval,'Coreia do Sul'), 
 (pais_seq.nextval,'Cosovo'), 
 (pais_seq.nextval,'Costa do Marfim'), 
 (pais_seq.nextval,'Costa Rica'), 
 (pais_seq.nextval,'Croácia'), 
 (pais_seq.nextval,'Cuaite'), 
 (pais_seq.nextval,'Cuba'), 
 (pais_seq.nextval,'Dinamarca'), 
 (pais_seq.nextval,'Dominica'), 
 (pais_seq.nextval,'Egito'), 
 (pais_seq.nextval,'Emirados Árabes Unidos'), 
 (pais_seq.nextval,'Equador'), 
 (pais_seq.nextval,'Eritreia'), 
 (pais_seq.nextval,'Eslováquia'), 
 (pais_seq.nextval,'Eslovénia'), 
 (pais_seq.nextval,'Espanha'), 
 (pais_seq.nextval,'Estado da Palestina'), 
 (pais_seq.nextval,'Estados Unidos'), 
 (pais_seq.nextval,'Estónia'), 
 (pais_seq.nextval,'Etiópia'), 
 (pais_seq.nextval,'Fiji'), 
 (pais_seq.nextval,'Filipinas'), 
 (pais_seq.nextval,'Finlândia'), 
 (pais_seq.nextval,'França'), 
 (pais_seq.nextval,'Gabão'), 
 (pais_seq.nextval,'Gâmbia'), 
 (pais_seq.nextval,'Gana'), 
 (pais_seq.nextval,'Geórgia'), 
 (pais_seq.nextval,'Granada'), 
 (pais_seq.nextval,'Grécia'), 
 (pais_seq.nextval,'Guatemala'), 
 (pais_seq.nextval,'Guiana'), 
 (pais_seq.nextval,'Guiné'), 
 (pais_seq.nextval,'Guiné Equatorial'), 
 (pais_seq.nextval,'Guiné-Bissau'), 
 (pais_seq.nextval,'Haiti'), 
 (pais_seq.nextval,'Honduras'), 
 (pais_seq.nextval,'Hungria'), 
 (pais_seq.nextval,'Iémen'), 
 (pais_seq.nextval,'Ilhas Marechal'), 
 (pais_seq.nextval,'Índia'), 
 (pais_seq.nextval,'Indonésia'), 
 (pais_seq.nextval,'Irão'), 
 (pais_seq.nextval,'Iraque'), 
 (pais_seq.nextval,'Irlanda'), 
 (pais_seq.nextval,'Islândia'), 
 (pais_seq.nextval,'Israel'), 
 (pais_seq.nextval,'Itália'), 
 (pais_seq.nextval,'Jamaica'), 
 (pais_seq.nextval,'Japão'), 
 (pais_seq.nextval,'Jibuti'), 
 (pais_seq.nextval,'Jordânia'), 
 (pais_seq.nextval,'Laus'), 
 (pais_seq.nextval,'Lesoto'), 
 (pais_seq.nextval,'Letónia'), 
 (pais_seq.nextval,'Líbano'), 
 (pais_seq.nextval,'Libéria'), 
 (pais_seq.nextval,'Líbia'), 
 (pais_seq.nextval,'Listenstaine'), 
 (pais_seq.nextval,'Lituânia'), 
 (pais_seq.nextval,'Luxemburgo'), 
 (pais_seq.nextval,'Macedónia'), 
 (pais_seq.nextval,'Madagáscar'), 
 (pais_seq.nextval,'Malásia'), 
 (pais_seq.nextval,'Maláui'), 
 (pais_seq.nextval,'Maldivas'), 
 (pais_seq.nextval,'Mali'), 
 (pais_seq.nextval,'Malta'), 
 (pais_seq.nextval,'Marrocos'), 
 (pais_seq.nextval,'Maurícia'), 
 (pais_seq.nextval,'Mauritânia'), 
 (pais_seq.nextval,'México'), 
 (pais_seq.nextval,'Mianmar'), 
 (pais_seq.nextval,'Micronésia'), 
 (pais_seq.nextval,'Moçambique'), 
 (pais_seq.nextval,'Moldávia'), 
 (pais_seq.nextval,'Mónaco'), 
 (pais_seq.nextval,'Mongólia'), 
 (pais_seq.nextval,'Montenegro'), 
 (pais_seq.nextval,'Namíbia'), 
 (pais_seq.nextval,'Nauru'), 
 (pais_seq.nextval,'Nepal'), 
 (pais_seq.nextval,'Nicarágua'), 
 (pais_seq.nextval,'Níger'), 
 (pais_seq.nextval,'Nigéria'), 
 (pais_seq.nextval,'Noruega'), 
 (pais_seq.nextval,'Nova Zelândia'), 
 (pais_seq.nextval,'Omã'), 
 (pais_seq.nextval,'Países Baixos'), 
 (pais_seq.nextval,'Palau'), 
 (pais_seq.nextval,'Panamá'), 
 (pais_seq.nextval,'Papua Nova Guiné'), 
 (pais_seq.nextval,'Paquistão'), 
 (pais_seq.nextval,'Paraguai'), 
 (pais_seq.nextval,'Peru'), 
 (pais_seq.nextval,'Polónia'), 
 (pais_seq.nextval,'Portugal'), 
 (pais_seq.nextval,'Quénia'), 
 (pais_seq.nextval,'Quirguistão'), 
 (pais_seq.nextval,'Quiribáti'), 
 (pais_seq.nextval,'Reino Unido'), 
 (pais_seq.nextval,'República Centro-Africana'), 
 (pais_seq.nextval,'República Checa'), 
 (pais_seq.nextval,'República Democrática do Congo'), 
 (pais_seq.nextval,'República Dominicana'), 
 (pais_seq.nextval,'Roménia'), 
 (pais_seq.nextval,'Ruanda'), 
 (pais_seq.nextval,'Rússia'), 
 (pais_seq.nextval,'Salomão'), 
 (pais_seq.nextval,'Salvador'), 
 (pais_seq.nextval,'Samoa'), 
 (pais_seq.nextval,'Santa Lúcia'), 
 (pais_seq.nextval,'São Cristóvão e Neves'), 
 (pais_seq.nextval,'São Marinho'), 
 (pais_seq.nextval,'São Tomé e Príncipe'), 
 (pais_seq.nextval,'São Vicente e Granadinas'), 
 (pais_seq.nextval,'Seicheles'), 
 (pais_seq.nextval,'Senegal'), 
 (pais_seq.nextval,'Serra Leoa'), 
 (pais_seq.nextval,'Sérvia'), 
 (pais_seq.nextval,'Singapura'), 
 (pais_seq.nextval,'Síria'), 
 (pais_seq.nextval,'Somália'), 
 (pais_seq.nextval,'Sri Lanca'), 
 (pais_seq.nextval,'Suazilândia'), 
 (pais_seq.nextval,'Sudão'), 
 (pais_seq.nextval,'Sudão do Sul'), 
 (pais_seq.nextval,'Suécia'), 
 (pais_seq.nextval,'Suíça'), 
 (pais_seq.nextval,'Suriname'), 
 (pais_seq.nextval,'Tailândia'), 
 (pais_seq.nextval,'Taiuã'), 
 (pais_seq.nextval,'Tajiquistão'), 
 (pais_seq.nextval,'Tanzânia'), 
 (pais_seq.nextval,'Timor-Leste'), 
 (pais_seq.nextval,'Togo'), 
 (pais_seq.nextval,'Tonga'), 
 (pais_seq.nextval,'Trindade e Tobago'), 
 (pais_seq.nextval,'Tunísia'), 
 (pais_seq.nextval,'Turcomenistão'), 
 (pais_seq.nextval,'Turquia'), 
 (pais_seq.nextval,'Tuvalu'), 
 (pais_seq.nextval,'Ucrânia'), 
 (pais_seq.nextval,'Uganda'), 
 (pais_seq.nextval,'Uruguai'), 
 (pais_seq.nextval,'Usbequistão'), 
 (pais_seq.nextval,'Vanuatu'), 
 (pais_seq.nextval,'Vaticano'), 
 (pais_seq.nextval,'Venezuela'), 
 (pais_seq.nextval,'Vietname'), 
 (pais_seq.nextval,'Zâmbia'), 
 (pais_seq.nextval,'Zimbábue');

 insert into estado values
 (estado_seq.nextval,  'AC', 26),
 (estado_seq.nextval,  'AL', 26),
 (estado_seq.nextval,  'AM', 26),
 (estado_seq.nextval,  'AP', 26),
 (estado_seq.nextval,  'BA', 26),
 (estado_seq.nextval,  'CE', 26),
 (estado_seq.nextval,  'DF', 26),
 (estado_seq.nextval,  'ES', 26),
 (estado_seq.nextval,  'GO', 26),
 (estado_seq.nextval,  'MA', 26),
 (estado_seq.nextval,  'MG', 26),
 (estado_seq.nextval,  'MS', 26),
 (estado_seq.nextval,  'MT', 26),
 (estado_seq.nextval,  'PA', 26),
 (estado_seq.nextval,  'PB', 26),
 (estado_seq.nextval,  'PE', 26),
 (estado_seq.nextval,  'PI', 26),
 (estado_seq.nextval,  'PR', 26),
 (estado_seq.nextval,  'RJ', 26),
 (estado_seq.nextval,  'RN', 26),
 (estado_seq.nextval,  'RO', 26),
 (estado_seq.nextval,  'RR', 26),
 (estado_seq.nextval,  'RS', 26),
 (estado_seq.nextval,  'SC', 26),
 (estado_seq.nextval,  'SE', 26),
 (estado_seq.nextval,  'SP', 26),
 (estado_seq.nextval,  'TO', 26);

 insert into cidade values
 (cidade_seq.nextval, 'Afonso Cláudio',  8),
 (cidade_seq.nextval, 'Baixo Guandu',  8),
 (cidade_seq.nextval, 'Cachoeiro de Itapemirim',  8),
 (cidade_seq.nextval, 'Divino de São Lourenço',  8),
 (cidade_seq.nextval, 'Ecoporanga',  8),
 (cidade_seq.nextval, 'Fundão',  8),
 (cidade_seq.nextval, 'Governador Lindenberg',  8),
 (cidade_seq.nextval, 'Ibatiba',  8),
 (cidade_seq.nextval, 'Jaguaré',  8),
 (cidade_seq.nextval, 'Laranja da Terra',  8),
 (cidade_seq.nextval, 'Mantenópolis',  8),
 (cidade_seq.nextval, 'Nova Venécia',  8),
 (cidade_seq.nextval, 'Pancas',  8),
 (cidade_seq.nextval, 'Rio Bananal',  8),
 (cidade_seq.nextval, 'Santa Leopoldina',  8),
 (cidade_seq.nextval, 'Vargem Alta',  8),
 (cidade_seq.nextval, 'Acrelândia',  1),
 (cidade_seq.nextval, 'Brasiléia',  1),
 (cidade_seq.nextval, 'Capixaba',  1),
 (cidade_seq.nextval, 'Epitaciolândia',  1),
 (cidade_seq.nextval, 'Feijó',  1),
 (cidade_seq.nextval, 'Jordão',  1),
 (cidade_seq.nextval, 'Mâncio Lima',  1),
 (cidade_seq.nextval, 'Plácido de Castro',  1),
 (cidade_seq.nextval, 'Rio Branco',  1),
 (cidade_seq.nextval, 'Santa Rosa do Purus',  1),
 (cidade_seq.nextval, 'Tarauacá',  1),
 (cidade_seq.nextval, 'Xapuri',  1),
 (cidade_seq.nextval, 'Água Branca',  2),
 (cidade_seq.nextval, 'Barra de Santo Antônio',  2),
 (cidade_seq.nextval, 'Cacimbinhas',  2),
 (cidade_seq.nextval, 'Delmiro Gouveia',  2),
 (cidade_seq.nextval, 'Estrela de Alagoas',  2),
 (cidade_seq.nextval, 'Feira Grande',  2),
 (cidade_seq.nextval, 'Girau do Ponciano',  2),
 (cidade_seq.nextval, 'Ibateguara',  2),
 (cidade_seq.nextval, 'Jacaré dos Homens',  2),
 (cidade_seq.nextval, 'Lagoa da Canoa',  2),
 (cidade_seq.nextval, 'Maceió',  2),
 (cidade_seq.nextval, 'Novo Lino',  2),
 (cidade_seq.nextval, 'Olho d`Água das Flores',  2),
 (cidade_seq.nextval, 'Palestina',  2),
 (cidade_seq.nextval, 'Quebrangulo',  2),
 (cidade_seq.nextval, 'Rio Largo',  2),
 (cidade_seq.nextval, 'Santa Luzia do Norte',  2),
 (cidade_seq.nextval, 'Tanque d`Arca',  2),
 (cidade_seq.nextval, 'União dos Palmares',  2),
 (cidade_seq.nextval, 'Viçosa',  2),
 (cidade_seq.nextval, 'Amapá',  4),
 (cidade_seq.nextval, 'Calçoene',  4),
 (cidade_seq.nextval, 'Ferreira Gomes',  4),
 (cidade_seq.nextval, 'Itaubal',  4),
 (cidade_seq.nextval, 'Laranjal do Jari',  4),
 (cidade_seq.nextval, 'Macapá',  4),
 (cidade_seq.nextval, 'Oiapoque',  4),
 (cidade_seq.nextval, 'Pedra Branca do Amaparí',  4),
 (cidade_seq.nextval, 'Santana',  4),
 (cidade_seq.nextval, 'Tartarugalzinho',  4),
 (cidade_seq.nextval, 'Vitória do Jari',  4),
 (cidade_seq.nextval, 'Alvarães',  3),
 (cidade_seq.nextval, 'Barcelos',  3),
 (cidade_seq.nextval, 'Caapiranga',  3),
 (cidade_seq.nextval, 'Eirunepé',  3),
 (cidade_seq.nextval, 'Fonte Boa',  3),
 (cidade_seq.nextval, 'Guajará',  3),
 (cidade_seq.nextval, 'Humaitá',  3),
 (cidade_seq.nextval, 'Ipixuna',  3),
 (cidade_seq.nextval, 'Japurá',  3),
 (cidade_seq.nextval, 'Lábrea',  3),
 (cidade_seq.nextval, 'Manacapuru',  3),
 (cidade_seq.nextval, 'Nhamundá',  3),
 (cidade_seq.nextval, 'Parintins',  3),
 (cidade_seq.nextval, 'Rio Preto da Eva',  3),
 (cidade_seq.nextval, 'Santa Isabel do Rio Negro',  3),
 (cidade_seq.nextval, 'Tabatinga',  3),
 (cidade_seq.nextval, 'Uarini',  3),
 (cidade_seq.nextval, 'Abaíra',  5),
 (cidade_seq.nextval, 'Baianópolis',  5),
 (cidade_seq.nextval, 'Caatiba',  5),
 (cidade_seq.nextval, 'Dário Meira',  5),
 (cidade_seq.nextval, 'Elísio Medrado',  5),
 (cidade_seq.nextval, 'Fátima',  5),
 (cidade_seq.nextval, 'Gandu',  5),
 (cidade_seq.nextval, 'Heliópolis',  5),
 (cidade_seq.nextval, 'Jaborandi',  5),
 (cidade_seq.nextval, 'Lafaiete Coutinho',  5),
 (cidade_seq.nextval, 'Macajuba',  5),
 (cidade_seq.nextval, 'Nazaré',  5),
 (cidade_seq.nextval, 'Olindina',  5),
 (cidade_seq.nextval, 'Palmas de Monte Alto',  5),
 (cidade_seq.nextval, 'Queimadas',  5),
 (cidade_seq.nextval, 'Rafael Jambeiro',  5),
 (cidade_seq.nextval, 'Salinas da Margarida',  5),
 (cidade_seq.nextval, 'Salvador',  5),
 (cidade_seq.nextval, 'Tanhaçu',  5),
 (cidade_seq.nextval, 'Ubaíra',  5),
 (cidade_seq.nextval, 'Valença',  5),
 (cidade_seq.nextval, 'Wagner',  5),
 (cidade_seq.nextval, 'Xique-Xique',  5),
 (cidade_seq.nextval, 'Abaiara',  6),
 (cidade_seq.nextval, 'Baixio',  6),
 (cidade_seq.nextval, 'Camocim',  6),
 (cidade_seq.nextval, 'Campos Sales',  6),
 (cidade_seq.nextval, 'Canindé',  6),
 (cidade_seq.nextval, 'Capistrano',  6),
 (cidade_seq.nextval, 'Caridade',  6),
 (cidade_seq.nextval, 'Cariré',  6),
 (cidade_seq.nextval, 'Caririaçu',  6),
 (cidade_seq.nextval, 'Cariús',  6),
 (cidade_seq.nextval, 'Carnaubal',  6),
 (cidade_seq.nextval, 'Umirim',  6),
 (cidade_seq.nextval, 'Uruburetama',  6),
 (cidade_seq.nextval, 'Uruoca',  6),
 (cidade_seq.nextval, 'Varjota',  6),
 (cidade_seq.nextval, 'Várzea Alegre',  6),
 (cidade_seq.nextval, 'Viçosa do Ceará',  6),
 (cidade_seq.nextval, 'Brasília',  7),
 (cidade_seq.nextval, 'Abadia de Goiás',  9),
 (cidade_seq.nextval, 'Abadiânia',  9),
 (cidade_seq.nextval, 'Acreúna',  9),
 (cidade_seq.nextval, 'Adelândia',  9),
 (cidade_seq.nextval, 'Água Fria de Goiás',  9),
 (cidade_seq.nextval, 'Água Limpa',  9),
 (cidade_seq.nextval, 'Águas Lindas de Goiás',  9),
 (cidade_seq.nextval, 'Alexânia',  9),
 (cidade_seq.nextval, 'Aloândia',  9),
 (cidade_seq.nextval, 'Alto Horizonte',  9),
 (cidade_seq.nextval, 'Alto Paraíso de Goiás',  9),
 (cidade_seq.nextval, 'Alvorada do Norte',  9),
 (cidade_seq.nextval, 'Amaralina',  9),
 (cidade_seq.nextval, 'Americano do Brasil',  9),
 (cidade_seq.nextval, 'Amorinópolis',  9),
 (cidade_seq.nextval, 'Anápolis',  9),
 (cidade_seq.nextval, 'Anhanguera',  9),
 (cidade_seq.nextval, 'Anicuns',  9),
 (cidade_seq.nextval, 'Aparecida de Goiânia',  9),
 (cidade_seq.nextval, 'Aparecida do Rio Doce',  9),
 (cidade_seq.nextval, 'Aporé',  9),
 (cidade_seq.nextval, 'Araçu',  9),
 (cidade_seq.nextval, 'Aragarças',  9),
 (cidade_seq.nextval, 'Aragoiânia',  9),
 (cidade_seq.nextval, 'Araguapaz',  9),
 (cidade_seq.nextval, 'Arenópolis',  9),
 (cidade_seq.nextval, 'Aruanã',  9),
 (cidade_seq.nextval, 'Aurilândia',  9),
 (cidade_seq.nextval, 'Brazabrantes',  9),
 (cidade_seq.nextval, 'Britânia',  9),
 (cidade_seq.nextval, 'Buriti Alegre',  9),
 (cidade_seq.nextval, 'Buriti de Goiás',  9),
 (cidade_seq.nextval, 'Buritinópolis',  9),
 (cidade_seq.nextval, 'Alto Alegre do Pindaré',  10),
 (cidade_seq.nextval, 'Alto Parnaíba',  10),
 (cidade_seq.nextval, 'Amapá do Maranhão',  10),
 (cidade_seq.nextval, 'Amarante do Maranhão',  10),
 (cidade_seq.nextval, 'Anajatuba',  10),
 (cidade_seq.nextval, 'Anapurus',  10),
 (cidade_seq.nextval, 'Apicum-Açu',  10),
 (cidade_seq.nextval, 'Araguanã',  10),
 (cidade_seq.nextval, 'Araioses',  10),
 (cidade_seq.nextval, 'Arame',  10),
 (cidade_seq.nextval, 'Arari',  10),
 (cidade_seq.nextval, 'Axixá',  10),
 (cidade_seq.nextval, 'Bacabal',  10),
 (cidade_seq.nextval, 'Bacabeira',  10),
 (cidade_seq.nextval, 'Bacuri',  10),
 (cidade_seq.nextval, 'Bacurituba',  10),
 (cidade_seq.nextval, 'Balsas',  10),
 (cidade_seq.nextval, 'Barão de Grajaú',  10),
 (cidade_seq.nextval, 'Barra do Corda',  10),
 (cidade_seq.nextval, 'Barreirinhas',  10),
 (cidade_seq.nextval, 'Senador La Rocque',  10),
 (cidade_seq.nextval, 'Serrano do Maranhão',  10),
 (cidade_seq.nextval, 'Sítio Novo',  10),
 (cidade_seq.nextval, 'Sucupira do Norte',  10),
 (cidade_seq.nextval, 'Sucupira do Riachão',  10),
 (cidade_seq.nextval, 'Tasso Fragoso',  10),
 (cidade_seq.nextval, 'Timbiras',  10),
 (cidade_seq.nextval, 'Timon',  10),
 (cidade_seq.nextval, 'Trizidela do Vale',  10),
 (cidade_seq.nextval, 'Tufilândia',  10),
 (cidade_seq.nextval, 'Tuntum',  10),
 (cidade_seq.nextval, 'Turiaçu',  10),
 (cidade_seq.nextval, 'Turilândia',  10),
 (cidade_seq.nextval, 'Tutóia',  10),
 (cidade_seq.nextval, 'Urbano Santos',  10),
 (cidade_seq.nextval, 'Vargem Grande',  10),
 (cidade_seq.nextval, 'Viana',  10),
 (cidade_seq.nextval, 'Vila Nova dos Martírios',  10),
 (cidade_seq.nextval, 'Vitória do Mearim',  10),
 (cidade_seq.nextval, 'Vitorino Freire',  10),
 (cidade_seq.nextval, 'Zé Doca',  10),
 (cidade_seq.nextval, 'Acorizal',  13),
 (cidade_seq.nextval, 'Água Boa',  13),
 (cidade_seq.nextval, 'Alta Floresta',  13),
 (cidade_seq.nextval, 'Alto Araguaia',  13),
 (cidade_seq.nextval, 'Alto Boa Vista',  13),
 (cidade_seq.nextval, 'Alto Garças',  13),
 (cidade_seq.nextval, 'Alto Paraguai',  13),
 (cidade_seq.nextval, 'Alto Taquari',  13),
 (cidade_seq.nextval, 'Apiacás',  13),
 (cidade_seq.nextval, 'Araguaiana',  13),
 (cidade_seq.nextval, 'Araguainha',  13),
 (cidade_seq.nextval, 'Araputanga',  13),
 (cidade_seq.nextval, 'Arenápolis',  13),
 (cidade_seq.nextval, 'Aripuanã',  13),
 (cidade_seq.nextval, 'Barão de Melgaço',  13),
 (cidade_seq.nextval, 'Barra do Bugres',  13),
 (cidade_seq.nextval, 'Barra do Garças',  13),
 (cidade_seq.nextval, 'Bom Jesus do Araguaia',  13),
 (cidade_seq.nextval, 'Brasnorte',  13),
 (cidade_seq.nextval, 'Cáceres',  13),
 (cidade_seq.nextval, 'Campinápolis',  13),
 (cidade_seq.nextval, 'Campo Novo do Parecis',  13),
 (cidade_seq.nextval, 'Campo Verde',  13),
 (cidade_seq.nextval, 'Campos de Júlio',  13),
 (cidade_seq.nextval, 'Canabrava do Norte',  13),
 (cidade_seq.nextval, 'Canarana',  13),
 (cidade_seq.nextval, 'Carlinda',  13),
 (cidade_seq.nextval, 'Castanheira',  13),
 (cidade_seq.nextval, 'Chapada dos Guimarães',  13),
 (cidade_seq.nextval, 'Cláudia',  13),
 (cidade_seq.nextval, 'Cocalinho',  13),
 (cidade_seq.nextval, 'Colíder',  13),
 (cidade_seq.nextval, 'Colniza',  13),
 (cidade_seq.nextval, 'Comodoro',  13),
 (cidade_seq.nextval, 'Nova Canaã do Norte',  13),
 (cidade_seq.nextval, 'Nova Guarita',  13),
 (cidade_seq.nextval, 'Nova Lacerda',  13),
 (cidade_seq.nextval, 'Nova Marilândia',  13),
 (cidade_seq.nextval, 'Nova Maringá',  13),
 (cidade_seq.nextval, 'Nova Monte verde',  13),
 (cidade_seq.nextval, 'Nova Mutum',  13),
 (cidade_seq.nextval, 'Nova Olímpia',  13),
 (cidade_seq.nextval, 'Nova Santa Helena',  13),
 (cidade_seq.nextval, 'Nova Ubiratã',  13),
 (cidade_seq.nextval, 'Nova Xavantina',  13),
 (cidade_seq.nextval, 'Novo Horizonte do Norte',  13),
 (cidade_seq.nextval, 'Novo Mundo',  13),
 (cidade_seq.nextval, 'Novo Santo Antônio',  13),
 (cidade_seq.nextval, 'Novo São Joaquim',  13),
 (cidade_seq.nextval, 'Paranaíta',  13),
 (cidade_seq.nextval, 'Paranatinga',  13),
 (cidade_seq.nextval, 'Pedra Preta',  13),
 (cidade_seq.nextval, 'Peixoto de Azevedo',  13),
 (cidade_seq.nextval, 'Planalto da Serra',  13),
 (cidade_seq.nextval, 'Poconé',  13),
 (cidade_seq.nextval, 'Pontal do Araguaia',  13),
 (cidade_seq.nextval, 'Ponte Branca',  13),
 (cidade_seq.nextval, 'Pontes e Lacerda',  13),
 (cidade_seq.nextval, 'Porto Alegre do Norte',  13),
 (cidade_seq.nextval, 'Porto dos Gaúchos',  13),
 (cidade_seq.nextval, 'Porto Esperidião',  13),
 (cidade_seq.nextval, 'Porto Estrela',  13),
 (cidade_seq.nextval, 'Poxoréo',  13),
 (cidade_seq.nextval, 'Primavera do Leste',  13),
 (cidade_seq.nextval, 'Querência',  13),
 (cidade_seq.nextval, 'Reserva do Cabaçal',  13),
 (cidade_seq.nextval, 'Ribeirão Cascalheira',  13),
 (cidade_seq.nextval, 'Ribeirãozinho',  13),
 (cidade_seq.nextval, 'Rio Branco',  13),
 (cidade_seq.nextval, 'Rondolândia',  13),
 (cidade_seq.nextval, 'Rondonópolis',  13),
 (cidade_seq.nextval, 'Rosário Oeste',  13),
 (cidade_seq.nextval, 'Salto do Céu',  13),
 (cidade_seq.nextval, 'Santa Carmem',  13),
 (cidade_seq.nextval, 'Santa Cruz do Xingu',  13),
 (cidade_seq.nextval, 'Santa Rita do Trivelato',  13),
 (cidade_seq.nextval, 'Santa Terezinha',  13),
 (cidade_seq.nextval, 'Santo Afonso',  13),
 (cidade_seq.nextval, 'Santo Antônio do Leste',  13),
 (cidade_seq.nextval, 'Santo Antônio do Leverger',  13),
 (cidade_seq.nextval, 'São Félix do Araguaia',  13),
 (cidade_seq.nextval, 'São José do Povo',  13),
 (cidade_seq.nextval, 'São José do Rio Claro',  13),
 (cidade_seq.nextval, 'São José do Xingu',  13),
 (cidade_seq.nextval, 'São José dos Quatro Marcos',  13),
 (cidade_seq.nextval, 'São Pedro da Cipa',  13),
 (cidade_seq.nextval, 'Sapezal',  13),
 (cidade_seq.nextval, 'Serra Nova Dourada',  13),
 (cidade_seq.nextval, 'Sinop',  13),
 (cidade_seq.nextval, 'Sorriso',  13),
 (cidade_seq.nextval, 'Tabaporã',  13),
 (cidade_seq.nextval, 'Tangará da Serra',  13),
 (cidade_seq.nextval, 'Vila Rica',  13),
 (cidade_seq.nextval, 'Douradina',  12),
 (cidade_seq.nextval, 'Dourados',  12),
 (cidade_seq.nextval, 'Eldorado',  12),
 (cidade_seq.nextval, 'Fátima do Sul',  12),
 (cidade_seq.nextval, 'Figueirão',  12),
 (cidade_seq.nextval, 'Glória de Dourados',  12),
 (cidade_seq.nextval, 'Guia Lopes da Laguna',  12),
 (cidade_seq.nextval, 'Iguatemi',  12),
 (cidade_seq.nextval, 'Inocência',  12),
 (cidade_seq.nextval, 'Itaporã',  12),
 (cidade_seq.nextval, 'Itaquiraí',  12),
 (cidade_seq.nextval, 'Ivinhema',  12),
 (cidade_seq.nextval, 'Japorã',  12),
 (cidade_seq.nextval, 'Jaraguari',  12),
 (cidade_seq.nextval, 'Jardim',  12),
 (cidade_seq.nextval, 'Jateí',  12),
 (cidade_seq.nextval, 'Juti',  12),
 (cidade_seq.nextval, 'Ladário',  12),
 (cidade_seq.nextval, 'Laguna Carapã',  12),
 (cidade_seq.nextval, 'Maracaju',  12),
 (cidade_seq.nextval, 'Miranda',  12),
 (cidade_seq.nextval, 'Mundo Novo',  12),
 (cidade_seq.nextval, 'Naviraí',  12),
 (cidade_seq.nextval, 'Nioaque',  12),
 (cidade_seq.nextval, 'Nova Alvorada do Sul',  12),
 (cidade_seq.nextval, 'Nova Andradina',  12),
 (cidade_seq.nextval, 'Novo Horizonte do Sul',  12),
 (cidade_seq.nextval, 'Paranaíba',  12),
 (cidade_seq.nextval, 'Paranhos',  12),
 (cidade_seq.nextval, 'Pedro Gomes',  12),
 (cidade_seq.nextval, 'Ponta Porã',  12),
 (cidade_seq.nextval, 'Porto Murtinho',  12),
 (cidade_seq.nextval, 'Ribas do Rio Pardo',  12),
 (cidade_seq.nextval, 'Rio Brilhante',  12),
 (cidade_seq.nextval, 'Rio Negro',  12),
 (cidade_seq.nextval, 'Rio Verde de Mato Grosso',  12),
 (cidade_seq.nextval, 'Rochedo',  12),
 (cidade_seq.nextval, 'Santa Rita do Pardo',  12),
 (cidade_seq.nextval, 'São Gabriel do Oeste',  12),
 (cidade_seq.nextval, 'Selvíria',  12),
 (cidade_seq.nextval, 'Sete Quedas',  12),
 (cidade_seq.nextval, 'Sidrolândia',  12),
 (cidade_seq.nextval, 'Sonora',  12),
 (cidade_seq.nextval, 'Tacuru',  12),
 (cidade_seq.nextval, 'Taquarussu',  12),
 (cidade_seq.nextval, 'Terenos',  12),
 (cidade_seq.nextval, 'Três Lagoas',  12),
 (cidade_seq.nextval, 'Vicentina',  12),
 (cidade_seq.nextval, 'Abadia dos Dourados',  11),
 (cidade_seq.nextval, 'Abaeté',  11),
 (cidade_seq.nextval, 'Senhora de Oliveira',  11),
 (cidade_seq.nextval, 'Senhora do Porto',  11),
 (cidade_seq.nextval, 'Senhora dos Remédios',  11),
 (cidade_seq.nextval, 'Sericita',  11),
 (cidade_seq.nextval, 'Seritinga',  11),
 (cidade_seq.nextval, 'Serra Azul de Minas',  11),
 (cidade_seq.nextval, 'Serra da Saudade',  11),
 (cidade_seq.nextval, 'Serra do Salitre',  11),
 (cidade_seq.nextval, 'Serra dos Aimorés',  11),
 (cidade_seq.nextval, 'Serrania',  11),
 (cidade_seq.nextval, 'Serranópolis de Minas',  11),
 (cidade_seq.nextval, 'Serranos',  11),
 (cidade_seq.nextval, 'Serro',  11),
 (cidade_seq.nextval, 'Sete Lagoas',  11),
 (cidade_seq.nextval, 'Setubinha',  11),
 (cidade_seq.nextval, 'Silveirânia',  11),
 (cidade_seq.nextval, 'Silvianópolis',  11),
 (cidade_seq.nextval, 'Simão Pereira',  11),
 (cidade_seq.nextval, 'Simonésia',  11),
 (cidade_seq.nextval, 'Sobrália',  11),
 (cidade_seq.nextval, 'Soledade de Minas',  11),
 (cidade_seq.nextval, 'Tabuleiro',  11),
 (cidade_seq.nextval, 'Taiobeiras',  11),
 (cidade_seq.nextval, 'Taparuba',  11),
 (cidade_seq.nextval, 'Tapira',  11),
 (cidade_seq.nextval, 'Tapiraí',  11),
 (cidade_seq.nextval, 'Taquaraçu de Minas',  11),
 (cidade_seq.nextval, 'Tarumirim',  11),
 (cidade_seq.nextval, 'Teixeiras',  11),
 (cidade_seq.nextval, 'Teófilo Otoni',  11),
 (cidade_seq.nextval, 'Timóteo',  11),
 (cidade_seq.nextval, 'Tiradentes',  11),
 (cidade_seq.nextval, 'Tiros',  11),
 (cidade_seq.nextval, 'Tocantins',  11),
 (cidade_seq.nextval, 'Tocos do Moji',  11),
 (cidade_seq.nextval, 'Toledo',  11),
 (cidade_seq.nextval, 'Tombos',  11),
 (cidade_seq.nextval, 'Três Corações',  11),
 (cidade_seq.nextval, 'Três Marias',  11),
 (cidade_seq.nextval, 'Três Pontas',  11),
 (cidade_seq.nextval, 'Tumiritinga',  11),
 (cidade_seq.nextval, 'Tupaciguara',  11),
 (cidade_seq.nextval, 'Turmalina',  11),
 (cidade_seq.nextval, 'Turvolândia',  11),
 (cidade_seq.nextval, 'Ubá',  11),
 (cidade_seq.nextval, 'Ubaí',  11),
 (cidade_seq.nextval, 'Ubaporanga',  11),
 (cidade_seq.nextval, 'Uberaba',  11),
 (cidade_seq.nextval, 'Uberlândia',  11),
 (cidade_seq.nextval, 'Umburatiba',  11),
 (cidade_seq.nextval, 'Unaí',  11),
 (cidade_seq.nextval, 'União de Minas',  11),
 (cidade_seq.nextval, 'Uruana de Minas',  11),
 (cidade_seq.nextval, 'Urucânia',  11),
 (cidade_seq.nextval, 'Urucuia',  11),
 (cidade_seq.nextval, 'Vargem Alegre',  11),
 (cidade_seq.nextval, 'Vargem Bonita',  11),
 (cidade_seq.nextval, 'Vargem Grande do Rio Pardo',  11),
 (cidade_seq.nextval, 'Varginha',  11),
 (cidade_seq.nextval, 'Varjão de Minas',  11),
 (cidade_seq.nextval, 'Várzea da Palma',  11),
 (cidade_seq.nextval, 'Varzelândia',  11),
 (cidade_seq.nextval, 'Vazante',  11),
 (cidade_seq.nextval, 'Verdelândia',  11),
 (cidade_seq.nextval, 'Veredinha',  11),
 (cidade_seq.nextval, 'Veríssimo',  11),
 (cidade_seq.nextval, 'Vermelho Novo',  11),
 (cidade_seq.nextval, 'Vespasiano',  11),
 (cidade_seq.nextval, 'Viçosa',  11),
 (cidade_seq.nextval, 'Vieiras',  11),
 (cidade_seq.nextval, 'Virgem da Lapa',  11),
 (cidade_seq.nextval, 'Virgínia',  11),
 (cidade_seq.nextval, 'Virginópolis',  11),
 (cidade_seq.nextval, 'Virgolândia',  11),
 (cidade_seq.nextval, 'Visconde do Rio Branco',  11),
 (cidade_seq.nextval, 'Volta Grande',  11),
 (cidade_seq.nextval, 'Wenceslau Braz',  11),
 (cidade_seq.nextval, 'Abaetetuba',  14),
 (cidade_seq.nextval, 'Abel Figueiredo',  14),
 (cidade_seq.nextval, 'Acará',  14),
 (cidade_seq.nextval, 'Afuá',  14),
 (cidade_seq.nextval, 'Água Azul do Norte',  14),
 (cidade_seq.nextval, 'Alenquer',  14),
 (cidade_seq.nextval, 'Almeirim',  14),
 (cidade_seq.nextval, 'Altamira',  14),
 (cidade_seq.nextval, 'Anajás',  14),
 (cidade_seq.nextval, 'Ananindeua',  14),
 (cidade_seq.nextval, 'Anapu',  14),
 (cidade_seq.nextval, 'Augusto Corrêa',  14),
 (cidade_seq.nextval, 'Aurora do Pará',  14),
 (cidade_seq.nextval, 'Aveiro',  14),
 (cidade_seq.nextval, 'Óbidos',  14),
 (cidade_seq.nextval, 'Oeiras do Pará',  14),
 (cidade_seq.nextval, 'Oriximiná',  14),
 (cidade_seq.nextval, 'Ourém',  14),
 (cidade_seq.nextval, 'Ourilândia do Norte',  14),
 (cidade_seq.nextval, 'Pacajá',  14),
 (cidade_seq.nextval, 'Palestina do Pará',  14),
 (cidade_seq.nextval, 'Paragominas',  14),
 (cidade_seq.nextval, 'Parauapebas',  14),
 (cidade_seq.nextval, 'Pau d`Arco',  14),
 (cidade_seq.nextval, 'Peixe-Boi',  14),
 (cidade_seq.nextval, 'Piçarra',  14),
 (cidade_seq.nextval, 'Placas',  14),
 (cidade_seq.nextval, 'Ponta de Pedras',  14),
 (cidade_seq.nextval, 'Portel',  14),
 (cidade_seq.nextval, 'Porto de Moz',  14),
 (cidade_seq.nextval, 'Prainha',  14),
 (cidade_seq.nextval, 'Primavera',  14),
 (cidade_seq.nextval, 'Quatipuru',  14),
 (cidade_seq.nextval, 'Redenção',  14),
 (cidade_seq.nextval, 'Rio Maria',  14),
 (cidade_seq.nextval, 'Rondon do Pará',  14),
 (cidade_seq.nextval, 'Rurópolis',  14),
 (cidade_seq.nextval, 'Salinópolis',  14),
 (cidade_seq.nextval, 'Salvaterra',  14),
 (cidade_seq.nextval, 'Santa Bárbara do Pará',  14),
 (cidade_seq.nextval, 'Santa Cruz do Arari',  14),
 (cidade_seq.nextval, 'Santa Isabel do Pará',  14),
 (cidade_seq.nextval, 'Santa Luzia do Pará',  14),
 (cidade_seq.nextval, 'Santa Maria das Barreiras',  14),
 (cidade_seq.nextval, 'Santa Maria do Pará',  14),
 (cidade_seq.nextval, 'Santana do Araguaia',  14),
 (cidade_seq.nextval, 'Santarém',  14),
 (cidade_seq.nextval, 'Santarém Novo',  14),
 (cidade_seq.nextval, 'Santo Antônio do Tauá',  14),
 (cidade_seq.nextval, 'São Caetano de Odivelas',  14),
 (cidade_seq.nextval, 'São Domingos do Araguaia',  14),
 (cidade_seq.nextval, 'São Domingos do Capim',  14),
 (cidade_seq.nextval, 'São Félix do Xingu',  14),
 (cidade_seq.nextval, 'São Francisco do Pará',  14),
 (cidade_seq.nextval, 'São Geraldo do Araguaia',  14),
 (cidade_seq.nextval, 'São João da Ponta',  14),
 (cidade_seq.nextval, 'São João de Pirabas',  14),
 (cidade_seq.nextval, 'São João do Araguaia',  14),
 (cidade_seq.nextval, 'São Miguel do Guamá',  14),
 (cidade_seq.nextval, 'São Sebastião da Boa Vista',  14),
 (cidade_seq.nextval, 'Sapucaia',  14),
 (cidade_seq.nextval, 'Senador José Porfírio',  14),
 (cidade_seq.nextval, 'Soure',  14),
 (cidade_seq.nextval, 'Tailândia',  14),
 (cidade_seq.nextval, 'Terra Alta',  14),
 (cidade_seq.nextval, 'Terra Santa',  14),
 (cidade_seq.nextval, 'Tomé-Açu',  14),
 (cidade_seq.nextval, 'Tracuateua',  14),
 (cidade_seq.nextval, 'Trairão',  14),
 (cidade_seq.nextval, 'Tucumã',  14),
 (cidade_seq.nextval, 'Tucuruí',  14),
 (cidade_seq.nextval, 'Ulianópolis',  14),
 (cidade_seq.nextval, 'Uruará',  14),
 (cidade_seq.nextval, 'Vigia',  14),
 (cidade_seq.nextval, 'Viseu',  14),
 (cidade_seq.nextval, 'Vitória do Xingu',  14),
 (cidade_seq.nextval, 'Xinguara',  14),
 (cidade_seq.nextval, 'Água Branca',  15),
 (cidade_seq.nextval, 'Aguiar',  15),
 (cidade_seq.nextval, 'Alagoa Grande',  15),
 (cidade_seq.nextval, 'Alagoa Nova',  15),
 (cidade_seq.nextval, 'Alagoinha',  15),
 (cidade_seq.nextval, 'Alcantil',  15),
 (cidade_seq.nextval, 'Algodão de Jandaíra',  15),
 (cidade_seq.nextval, 'Alhandra',  15),
 (cidade_seq.nextval, 'Malta',  15),
 (cidade_seq.nextval, 'Mamanguape',  15),
 (cidade_seq.nextval, 'Manaíra',  15),
 (cidade_seq.nextval, 'Marcação',  15),
 (cidade_seq.nextval, 'Mari',  15),
 (cidade_seq.nextval, 'Marizópolis',  15),
 (cidade_seq.nextval, 'Massaranduba',  15),
 (cidade_seq.nextval, 'Mataraca',  15),
 (cidade_seq.nextval, 'Queimadas',  15),
 (cidade_seq.nextval, 'Quixabá',  15),
 (cidade_seq.nextval, 'Remígio',  15),
 (cidade_seq.nextval, 'Riachão',  15),
 (cidade_seq.nextval, 'Riachão do Bacamarte',  15),
 (cidade_seq.nextval, 'Riachão do Poço',  15),
 (cidade_seq.nextval, 'Riacho de Santo Antônio',  15),
 (cidade_seq.nextval, 'Riacho dos Cavalos',  15),
 (cidade_seq.nextval, 'Rio Tinto',  15),
 (cidade_seq.nextval, 'Salgadinho',  15),
 (cidade_seq.nextval, 'Salgado de São Félix',  15),
 (cidade_seq.nextval, 'Santa Cecília',  15),
 (cidade_seq.nextval, 'Santa Cruz',  15),
 (cidade_seq.nextval, 'Santa Helena',  15),
 (cidade_seq.nextval, 'Santa Inês',  15),
 (cidade_seq.nextval, 'Santa Luzia',  15),
 (cidade_seq.nextval, 'Santa Rita',  15),
 (cidade_seq.nextval, 'Santa Teresinha',  15),
 (cidade_seq.nextval, 'Santana de Mangueira',  15),
 (cidade_seq.nextval, 'Santana dos Garrotes',  15),
 (cidade_seq.nextval, 'Santarém',  15),
 (cidade_seq.nextval, 'Santo André',  15),
 (cidade_seq.nextval, 'São Bentinho',  15),
 (cidade_seq.nextval, 'São Bento',  15),
 (cidade_seq.nextval, 'São Domingos de Pombal',  15),
 (cidade_seq.nextval, 'São Domingos do Cariri',  15),
 (cidade_seq.nextval, 'São Francisco',  15),
 (cidade_seq.nextval, 'São João do Cariri',  15),
 (cidade_seq.nextval, 'São João do Rio do Peixe',  15),
 (cidade_seq.nextval, 'São João do Tigre',  15),
 (cidade_seq.nextval, 'São José da Lagoa Tapada',  15),
 (cidade_seq.nextval, 'São José de Caiana',  15),
 (cidade_seq.nextval, 'São José de Espinharas',  15),
 (cidade_seq.nextval, 'São José de Piranhas',  15),
 (cidade_seq.nextval, 'São José de Princesa',  15),
 (cidade_seq.nextval, 'São José do Bonfim',  15),
 (cidade_seq.nextval, 'São José do Brejo do Cruz',  15),
 (cidade_seq.nextval, 'São José do Sabugi',  15),
 (cidade_seq.nextval, 'São José dos Cordeiros',  15),
 (cidade_seq.nextval, 'São José dos Ramos',  15),
 (cidade_seq.nextval, 'São Mamede',  15),
 (cidade_seq.nextval, 'São Miguel de Taipu',  15),
 (cidade_seq.nextval, 'São Sebastião de Lagoa de Roça',  15),
 (cidade_seq.nextval, 'São Sebastião do Umbuzeiro',  15),
 (cidade_seq.nextval, 'Sapé',  15),
 (cidade_seq.nextval, 'Seridó',  15),
 (cidade_seq.nextval, 'Serra Branca',  15),
 (cidade_seq.nextval, 'Serra da Raiz',  15),
 (cidade_seq.nextval, 'Serra Grande',  15),
 (cidade_seq.nextval, 'Serra Redonda',  15),
 (cidade_seq.nextval, 'Serraria',  15),
 (cidade_seq.nextval, 'Sertãozinho',  15),
 (cidade_seq.nextval, 'Sobrado',  15),
 (cidade_seq.nextval, 'Solânea',  15),
 (cidade_seq.nextval, 'Soledade',  15),
 (cidade_seq.nextval, 'Sossêgo',  15),
 (cidade_seq.nextval, 'Sousa',  15),
 (cidade_seq.nextval, 'Sumé',  15),
 (cidade_seq.nextval, 'Taperoá',  15),
 (cidade_seq.nextval, 'Tavares',  15),
 (cidade_seq.nextval, 'Teixeira',  15),
 (cidade_seq.nextval, 'Tenório',  15),
 (cidade_seq.nextval, 'Triunfo',  15),
 (cidade_seq.nextval, 'Uiraúna',  15),
 (cidade_seq.nextval, 'Umbuzeiro',  15),
 (cidade_seq.nextval, 'Várzea',  15),
 (cidade_seq.nextval, 'Vieirópolis',  15),
 (cidade_seq.nextval, 'Vista Serrana',  15),
 (cidade_seq.nextval, 'Zabelê',  15),
 (cidade_seq.nextval, 'Abatiá',  18),
 (cidade_seq.nextval, 'Adrianópolis',  18),
 (cidade_seq.nextval, 'Agudos do Sul',  18),
 (cidade_seq.nextval, 'Almirante Tamandaré',  18),
 (cidade_seq.nextval, 'Altamira do Paraná',  18),
 (cidade_seq.nextval, 'Alto Paraíso',  18),
 (cidade_seq.nextval, 'Sabáudia',  18),
 (cidade_seq.nextval, 'Salgado Filho',  18),
 (cidade_seq.nextval, 'Salto do Itararé',  18),
 (cidade_seq.nextval, 'Salto do Lontra',  18),
 (cidade_seq.nextval, 'Santa Amélia',  18),
 (cidade_seq.nextval, 'Santa Cecília do Pavão',  18),
 (cidade_seq.nextval, 'Santa Cruz de Monte Castelo',  18),
 (cidade_seq.nextval, 'Santa Fé',  18),
 (cidade_seq.nextval, 'Santa Helena',  18),
 (cidade_seq.nextval, 'Santa Inês',  18),
 (cidade_seq.nextval, 'Santa Isabel do Ivaí',  18),
 (cidade_seq.nextval, 'Santa Izabel do Oeste',  18),
 (cidade_seq.nextval, 'Santa Lúcia',  18),
 (cidade_seq.nextval, 'Santa Maria do Oeste',  18),
 (cidade_seq.nextval, 'Santa Mariana',  18),
 (cidade_seq.nextval, 'Santa Mônica',  18),
 (cidade_seq.nextval, 'Santa Tereza do Oeste',  18),
 (cidade_seq.nextval, 'Santa Terezinha de Itaipu',  18),
 (cidade_seq.nextval, 'Santana do Itararé',  18),
 (cidade_seq.nextval, 'Santo Antônio da Platina',  18),
 (cidade_seq.nextval, 'Santo Antônio do Caiuá',  18),
 (cidade_seq.nextval, 'Santo Antônio do Paraíso',  18),
 (cidade_seq.nextval, 'Santo Antônio do Sudoeste',  18),
 (cidade_seq.nextval, 'Santo Inácio',  18),
 (cidade_seq.nextval, 'São Carlos do Ivaí',  18),
 (cidade_seq.nextval, 'São Jerônimo da Serra',  18),
 (cidade_seq.nextval, 'São João',  18),
 (cidade_seq.nextval, 'São João do Caiuá',  18),
 (cidade_seq.nextval, 'São João do Ivaí',  18),
 (cidade_seq.nextval, 'São João do Triunfo',  18),
 (cidade_seq.nextval, 'São Jorge d`Oeste',  18),
 (cidade_seq.nextval, 'São Jorge do Ivaí',  18),
 (cidade_seq.nextval, 'São Jorge do Patrocínio',  18),
 (cidade_seq.nextval, 'São José da Boa Vista',  18),
 (cidade_seq.nextval, 'São José das Palmeiras',  18),
 (cidade_seq.nextval, 'São José dos Pinhais',  18),
 (cidade_seq.nextval, 'São Manoel do Paraná',  18),
 (cidade_seq.nextval, 'São Mateus do Sul',  18),
 (cidade_seq.nextval, 'São Miguel do Iguaçu',  18),
 (cidade_seq.nextval, 'São Pedro do Iguaçu',  18),
 (cidade_seq.nextval, 'São Pedro do Ivaí',  18),
 (cidade_seq.nextval, 'São Pedro do Paraná',  18),
 (cidade_seq.nextval, 'São Sebastião da Amoreira',  18),
 (cidade_seq.nextval, 'São Tomé',  18),
 (cidade_seq.nextval, 'Sapopema',  18),
 (cidade_seq.nextval, 'Sarandi',  18),
 (cidade_seq.nextval, 'Saudade do Iguaçu',  18),
 (cidade_seq.nextval, 'Sengés',  18),
 (cidade_seq.nextval, 'Serranópolis do Iguaçu',  18),
 (cidade_seq.nextval, 'Sertaneja',  18),
 (cidade_seq.nextval, 'Sertanópolis',  18),
 (cidade_seq.nextval, 'Siqueira Campos',  18),
 (cidade_seq.nextval, 'Sulina',  18),
 (cidade_seq.nextval, 'Tamarana',  18),
 (cidade_seq.nextval, 'Tamboara',  18),
 (cidade_seq.nextval, 'Tapejara',  18),
 (cidade_seq.nextval, 'Tapira',  18),
 (cidade_seq.nextval, 'Teixeira Soares',  18),
 (cidade_seq.nextval, 'Telêmaco Borba',  18),
 (cidade_seq.nextval, 'Terra Boa',  18),
 (cidade_seq.nextval, 'Terra Rica',  18),
 (cidade_seq.nextval, 'Terra Roxa',  18),
 (cidade_seq.nextval, 'Tibagi',  18),
 (cidade_seq.nextval, 'Tijucas do Sul',  18),
 (cidade_seq.nextval, 'Toledo',  18),
 (cidade_seq.nextval, 'Tomazina',  18),
 (cidade_seq.nextval, 'Três Barras do Paraná',  18),
 (cidade_seq.nextval, 'Tunas do Paraná',  18),
 (cidade_seq.nextval, 'Tuneiras do Oeste',  18),
 (cidade_seq.nextval, 'Tupãssi',  18),
 (cidade_seq.nextval, 'Turvo',  18),
 (cidade_seq.nextval, 'Ubiratã',  18),
 (cidade_seq.nextval, 'Umuarama',  18),
 (cidade_seq.nextval, 'União da Vitória',  18),
 (cidade_seq.nextval, 'Uniflor',  18),
 (cidade_seq.nextval, 'Uraí',  18),
 (cidade_seq.nextval, 'Ventania',  18),
 (cidade_seq.nextval, 'Vera Cruz do Oeste',  18),
 (cidade_seq.nextval, 'Verê',  18),
 (cidade_seq.nextval, 'Virmond',  18),
 (cidade_seq.nextval, 'Vitorino',  18),
 (cidade_seq.nextval, 'Wenceslau Braz',  18),
 (cidade_seq.nextval, 'Xambrê',  18),
 (cidade_seq.nextval, 'Abreu e Lima',  16),
 (cidade_seq.nextval, 'Afogados da Ingazeira',  16),
 (cidade_seq.nextval, 'Afrânio',  16),
 (cidade_seq.nextval, 'Agrestina',  16),
 (cidade_seq.nextval, 'Água Preta',  16),
 (cidade_seq.nextval, 'Águas Belas',  16),
 (cidade_seq.nextval, 'Alagoinha',  16),
 (cidade_seq.nextval, 'Aliança',  16),
 (cidade_seq.nextval, 'Altinho',  16),
 (cidade_seq.nextval, 'Amaraji',  16),
 (cidade_seq.nextval, 'Angelim',  16),
 (cidade_seq.nextval, 'Araçoiaba',  16),
 (cidade_seq.nextval, 'Araripina',  16),
 (cidade_seq.nextval, 'Arcoverde',  16),
 (cidade_seq.nextval, 'Santa Maria do Cambucá',  16),
 (cidade_seq.nextval, 'Santa Terezinha',  16),
 (cidade_seq.nextval, 'São Benedito do Sul',  16),
 (cidade_seq.nextval, 'São Bento do Una',  16),
 (cidade_seq.nextval, 'São Caitano',  16),
 (cidade_seq.nextval, 'São João',  16),
 (cidade_seq.nextval, 'São Joaquim do Monte',  16),
 (cidade_seq.nextval, 'São José da Coroa Grande',  16),
 (cidade_seq.nextval, 'São José do Belmonte',  16),
 (cidade_seq.nextval, 'São José do Egito',  16),
 (cidade_seq.nextval, 'São Lourenço da Mata',  16),
 (cidade_seq.nextval, 'São Vicente Ferrer',  16),
 (cidade_seq.nextval, 'Serra Talhada',  16),
 (cidade_seq.nextval, 'Serrita',  16),
 (cidade_seq.nextval, 'Sertânia',  16),
 (cidade_seq.nextval, 'Sirinhaém',  16),
 (cidade_seq.nextval, 'Solidão',  16),
 (cidade_seq.nextval, 'Surubim',  16),
 (cidade_seq.nextval, 'Tabira',  16),
 (cidade_seq.nextval, 'Tacaimbó',  16),
 (cidade_seq.nextval, 'Tacaratu',  16),
 (cidade_seq.nextval, 'Tamandaré',  16),
 (cidade_seq.nextval, 'Taquaritinga do Norte',  16),
 (cidade_seq.nextval, 'Terezinha',  16),
 (cidade_seq.nextval, 'Terra Nova',  16),
 (cidade_seq.nextval, 'Timbaúba',  16),
 (cidade_seq.nextval, 'Toritama',  16),
 (cidade_seq.nextval, 'Tracunhaém',  16),
 (cidade_seq.nextval, 'Trindade',  16),
 (cidade_seq.nextval, 'Triunfo',  16),
 (cidade_seq.nextval, 'Tupanatinga',  16),
 (cidade_seq.nextval, 'Tuparetama',  16),
 (cidade_seq.nextval, 'Venturosa',  16),
 (cidade_seq.nextval, 'Verdejante',  16),
 (cidade_seq.nextval, 'Vertente do Lério',  16),
 (cidade_seq.nextval, 'Vertentes',  16),
 (cidade_seq.nextval, 'Vicência',  16),
 (cidade_seq.nextval, 'Vitória de Santo Antão',  16),
 (cidade_seq.nextval, 'Xexéu',  16),
 (cidade_seq.nextval, 'Acauã',  17),
 (cidade_seq.nextval, 'Agricolândia',  17),
 (cidade_seq.nextval, 'Água Branca',  17),
 (cidade_seq.nextval, 'Alagoinha do Piauí',  17),
 (cidade_seq.nextval, 'Alegrete do Piauí',  17),
 (cidade_seq.nextval, 'Alto Longá',  17),
 (cidade_seq.nextval, 'Altos',  17),
 (cidade_seq.nextval, 'Alvorada do Gurguéia',  17),
 (cidade_seq.nextval, 'Amarante',  17),
 (cidade_seq.nextval, 'Angical do Piauí',  17),
 (cidade_seq.nextval, 'Anísio de Abreu',  17),
 (cidade_seq.nextval, 'Antônio Almeida',  17),
 (cidade_seq.nextval, 'Aroazes',  17),
 (cidade_seq.nextval, 'Aroeiras do Itaim',  17),
 (cidade_seq.nextval, 'Arraial',  17),
 (cidade_seq.nextval, 'Assunção do Piauí',  17),
 (cidade_seq.nextval, 'Avelino Lopes',  17),
 (cidade_seq.nextval, 'Baixa Grande do Ribeiro',  17),
 (cidade_seq.nextval, 'Barra d`Alcântara',  17),
 (cidade_seq.nextval, 'Barras',  17),
 (cidade_seq.nextval, 'Vila Nova do Piauí',  17),
 (cidade_seq.nextval, 'Wall Ferraz',  17),
 (cidade_seq.nextval, 'Angra dos Reis',  19),
 (cidade_seq.nextval, 'Aperibé',  19),
 (cidade_seq.nextval, 'Araruama',  19),
 (cidade_seq.nextval, 'Mendes',  19),
 (cidade_seq.nextval, 'Mesquita',  19),
 (cidade_seq.nextval, 'Sapucaia',  19),
 (cidade_seq.nextval, 'Saquarema',  19),
 (cidade_seq.nextval, 'Seropédica',  19),
 (cidade_seq.nextval, 'Silva Jardim',  19),
 (cidade_seq.nextval, 'Sumidouro',  19),
 (cidade_seq.nextval, 'Tanguá',  19),
 (cidade_seq.nextval, 'Teresópolis',  19),
 (cidade_seq.nextval, 'Trajano de Morais',  19),
 (cidade_seq.nextval, 'Três Rios',  19),
 (cidade_seq.nextval, 'Valença',  19),
 (cidade_seq.nextval, 'Varre-Sai',  19),
 (cidade_seq.nextval, 'Vassouras',  19),
 (cidade_seq.nextval, 'Volta Redonda',  19),
 (cidade_seq.nextval, 'Acari',  20),
 (cidade_seq.nextval, 'Açu',  20),
 (cidade_seq.nextval, 'Afonso Bezerra',  20),
 (cidade_seq.nextval, 'Água Nova',  20),
 (cidade_seq.nextval, 'Alexandria',  20),
 (cidade_seq.nextval, 'Almino Afonso',  20),
 (cidade_seq.nextval, 'Alto do Rodrigues',  20),
 (cidade_seq.nextval, 'Angicos',  20),
 (cidade_seq.nextval, 'Antônio Martins',  20),
 (cidade_seq.nextval, 'Apodi',  20),
 (cidade_seq.nextval, 'Areia Branca',  20),
 (cidade_seq.nextval, 'Arês',  20),
 (cidade_seq.nextval, 'Augusto Severo',  20),
 (cidade_seq.nextval, 'Baía Formosa',  20),
 (cidade_seq.nextval, 'Baraúna',  20),
 (cidade_seq.nextval, 'Barcelona',  20),
 (cidade_seq.nextval, 'Bento Fernandes',  20),
 (cidade_seq.nextval, 'Bodó',  20),
 (cidade_seq.nextval, 'Bom Jesus',  20),
 (cidade_seq.nextval, 'Brejinho',  20),
 (cidade_seq.nextval, 'Caiçara do Norte',  20),
 (cidade_seq.nextval, 'Caiçara do Rio do Vento',  20),
 (cidade_seq.nextval, 'Caicó',  20),
 (cidade_seq.nextval, 'Campo Redondo',  20),
 (cidade_seq.nextval, 'Canguaretama',  20),
 (cidade_seq.nextval, 'Caraúbas',  20),
 (cidade_seq.nextval, 'Carnaúba dos Dantas',  20),
 (cidade_seq.nextval, 'Carnaubais',  20),
 (cidade_seq.nextval, 'Ceará-Mirim',  20),
 (cidade_seq.nextval, 'Taipu',  20),
 (cidade_seq.nextval, 'Tangará',  20),
 (cidade_seq.nextval, 'Tenente Ananias',  20),
 (cidade_seq.nextval, 'Tenente Laurentino Cruz',  20),
 (cidade_seq.nextval, 'Tibau',  20),
 (cidade_seq.nextval, 'Tibau do Sul',  20),
 (cidade_seq.nextval, 'Timbaúba dos Batistas',  20),
 (cidade_seq.nextval, 'Touros',  20),
 (cidade_seq.nextval, 'Triunfo Potiguar',  20),
 (cidade_seq.nextval, 'Umarizal',  20),
 (cidade_seq.nextval, 'Upanema',  20),
 (cidade_seq.nextval, 'Várzea',  20),
 (cidade_seq.nextval, 'Venha-Ver',  20),
 (cidade_seq.nextval, 'Vera Cruz',  20),
 (cidade_seq.nextval, 'Viçosa',  20),
 (cidade_seq.nextval, 'Vila Flor',  20),
 (cidade_seq.nextval, 'Aceguá',  23),
 (cidade_seq.nextval, 'Água Santa',  23),
 (cidade_seq.nextval, 'Agudo',  23),
 (cidade_seq.nextval, 'Ajuricaba',  23),
 (cidade_seq.nextval, 'Alecrim',  23),
 (cidade_seq.nextval, 'Alegrete',  23),
 (cidade_seq.nextval, 'Alegria',  23),
 (cidade_seq.nextval, 'Almirante Tamandaré do Sul',  23),
 (cidade_seq.nextval, 'Alpestre',  23),
 (cidade_seq.nextval, 'Alto Alegre',  23),
 (cidade_seq.nextval, 'Alto Feliz',  23),
 (cidade_seq.nextval, 'Alvorada',  23),
 (cidade_seq.nextval, 'Amaral Ferrador',  23),
 (cidade_seq.nextval, 'Augusto Pestana',  23),
 (cidade_seq.nextval, 'Áurea',  23),
 (cidade_seq.nextval, 'Bagé',  23),
 (cidade_seq.nextval, 'Balneário Pinhal',  23),
 (cidade_seq.nextval, 'Barão',  23),
 (cidade_seq.nextval, 'Barão de Cotegipe',  23),
 (cidade_seq.nextval, 'Barão do Triunfo',  23),
 (cidade_seq.nextval, 'Barra do Guarita',  23),
 (cidade_seq.nextval, 'Barra do Quaraí',  23),
 (cidade_seq.nextval, 'Barra do Ribeiro',  23),
 (cidade_seq.nextval, 'Barra do Rio Azul',  23),
 (cidade_seq.nextval, 'Barra Funda',  23),
 (cidade_seq.nextval, 'Barracão',  23),
 (cidade_seq.nextval, 'Barros Cassal',  23),
 (cidade_seq.nextval, 'Benjamin Constant do Sul',  23),
 (cidade_seq.nextval, 'Bento Gonçalves',  23),
 (cidade_seq.nextval, 'Boa Vista do Buricá',  23),
 (cidade_seq.nextval, 'Boa Vista do Cadeado',  23),
 (cidade_seq.nextval, 'Boa Vista do Incra',  23),
 (cidade_seq.nextval, 'Boa Vista do Sul',  23),
 (cidade_seq.nextval, 'Bom Jesus',  23),
 (cidade_seq.nextval, 'Bom Princípio',  23),
 (cidade_seq.nextval, 'Bom Progresso',  23),
 (cidade_seq.nextval, 'Bom Retiro do Sul',  23),
 (cidade_seq.nextval, 'Boqueirão do Leão',  23),
 (cidade_seq.nextval, 'Bossoroca',  23),
 (cidade_seq.nextval, 'Bozano',  23),
 (cidade_seq.nextval, 'Braga',  23),
 (cidade_seq.nextval, 'Brochier',  23),
 (cidade_seq.nextval, 'Butiá',  23),
 (cidade_seq.nextval, 'Caçapava do Sul',  23),
 (cidade_seq.nextval, 'Cacequi',  23),
 (cidade_seq.nextval, 'Cachoeira do Sul',  23),
 (cidade_seq.nextval, 'Cachoeirinha',  23),
 (cidade_seq.nextval, 'Cacique Doble',  23),
 (cidade_seq.nextval, 'Caibaté',  23),
 (cidade_seq.nextval, 'Caiçara',  23),
 (cidade_seq.nextval, 'Camaquã',  23),
 (cidade_seq.nextval, 'Camargo',  23),
 (cidade_seq.nextval, 'Cambará do Sul',  23),
 (cidade_seq.nextval, 'Campestre da Serra',  23),
 (cidade_seq.nextval, 'Campina das Missões',  23),
 (cidade_seq.nextval, 'Campinas do Sul',  23),
 (cidade_seq.nextval, 'Campo Bom',  23),
 (cidade_seq.nextval, 'Campo Novo',  23),
 (cidade_seq.nextval, 'Campos Borges',  23),
 (cidade_seq.nextval, 'Candelária',  23),
 (cidade_seq.nextval, 'Cândido Godói',  23),
 (cidade_seq.nextval, 'Candiota',  23),
 (cidade_seq.nextval, 'Canela',  23),
 (cidade_seq.nextval, 'Vista Gaúcha',  23),
 (cidade_seq.nextval, 'Vitória das Missões',  23),
 (cidade_seq.nextval, 'Westfália',  23),
 (cidade_seq.nextval, 'Xangri-lá',  23),
 (cidade_seq.nextval, 'Alta Floresta d`Oeste',  21),
 (cidade_seq.nextval, 'Alto Alegre dos Parecis',  21),
 (cidade_seq.nextval, 'Alto Paraíso',  21),
 (cidade_seq.nextval, 'Alvorada d`Oeste',  21),
 (cidade_seq.nextval, 'Ariquemes',  21),
 (cidade_seq.nextval, 'Buritis',  21),
 (cidade_seq.nextval, 'Santa Luzia d`Oeste',  21),
 (cidade_seq.nextval, 'São Felipe d`Oeste',  21),
 (cidade_seq.nextval, 'São Francisco do Guaporé',  21),
 (cidade_seq.nextval, 'São Miguel do Guaporé',  21),
 (cidade_seq.nextval, 'Seringueiras',  21),
 (cidade_seq.nextval, 'Teixeirópolis',  21),
 (cidade_seq.nextval, 'Theobroma',  21),
 (cidade_seq.nextval, 'Urupá',  21),
 (cidade_seq.nextval, 'Vale do Anari',  21),
 (cidade_seq.nextval, 'Vale do Paraíso',  21),
 (cidade_seq.nextval, 'Vilhena',  21),
 (cidade_seq.nextval, 'Alto Alegre',  22),
 (cidade_seq.nextval, 'Amajari',  22),
 (cidade_seq.nextval, 'Boa Vista',  22),
 (cidade_seq.nextval, 'Bonfim',  22),
 (cidade_seq.nextval, 'Cantá',  22),
 (cidade_seq.nextval, 'Caracaraí',  22),
 (cidade_seq.nextval, 'Caroebe',  22),
 (cidade_seq.nextval, 'Iracema',  22),
 (cidade_seq.nextval, 'Mucajaí',  22),
 (cidade_seq.nextval, 'Normandia',  22),
 (cidade_seq.nextval, 'Pacaraima',  22),
 (cidade_seq.nextval, 'Rorainópolis',  22),
 (cidade_seq.nextval, 'São João da Baliza',  22),
 (cidade_seq.nextval, 'São Luiz',  22),
 (cidade_seq.nextval, 'Uiramutã',  22),
 (cidade_seq.nextval, 'Abdon Batista',  24),
 (cidade_seq.nextval, 'Abelardo Luz',  24),
 (cidade_seq.nextval, 'Agrolândia',  24),
 (cidade_seq.nextval, 'Agronômica',  24),
 (cidade_seq.nextval, 'Imbuia',  24),
 (cidade_seq.nextval, 'Indaial',  24),
 (cidade_seq.nextval, 'Iomerê',  24),
 (cidade_seq.nextval, 'Ipira',  24),
 (cidade_seq.nextval, 'Iporã do Oeste',  24),
 (cidade_seq.nextval, 'Ipuaçu',  24),
 (cidade_seq.nextval, 'Ipumirim',  24),
 (cidade_seq.nextval, 'Iraceminha',  24),
 (cidade_seq.nextval, 'Irani',  24),
 (cidade_seq.nextval, 'Irati',  24),
 (cidade_seq.nextval, 'Irineópolis',  24),
 (cidade_seq.nextval, 'Itá',  24),
 (cidade_seq.nextval, 'Itaiópolis',  24),
 (cidade_seq.nextval, 'Itajaí',  24),
 (cidade_seq.nextval, 'Itapema',  24),
 (cidade_seq.nextval, 'Itapiranga',  24),
 (cidade_seq.nextval, 'Itapoá',  24),
 (cidade_seq.nextval, 'Ituporanga',  24),
 (cidade_seq.nextval, 'Jaborá',  24),
 (cidade_seq.nextval, 'Jacinto Machado',  24),
 (cidade_seq.nextval, 'Jaguaruna',  24),
 (cidade_seq.nextval, 'Jaraguá do Sul',  24),
 (cidade_seq.nextval, 'Jardinópolis',  24),
 (cidade_seq.nextval, 'Joaçaba',  24),
 (cidade_seq.nextval, 'Joinville',  24),
 (cidade_seq.nextval, 'José Boiteux',  24),
 (cidade_seq.nextval, 'Jupiá',  24),
 (cidade_seq.nextval, 'Lacerdópolis',  24),
 (cidade_seq.nextval, 'Xaxim',  24),
 (cidade_seq.nextval, 'Zortéa',  24),
 (cidade_seq.nextval, 'Álvaro de Carvalho',  26),
 (cidade_seq.nextval, 'Alvinlândia',  26),
 (cidade_seq.nextval, 'Americana',  26),
 (cidade_seq.nextval, 'Américo Brasiliense',  26),
 (cidade_seq.nextval, 'Américo de Campos',  26),
 (cidade_seq.nextval, 'Amparo',  26),
 (cidade_seq.nextval, 'Analândia',  26),
 (cidade_seq.nextval, 'Andradina',  26),
 (cidade_seq.nextval, 'Angatuba',  26),
 (cidade_seq.nextval, 'Anhembi',  26),
 (cidade_seq.nextval, 'Anhumas',  26),
 (cidade_seq.nextval, 'Aparecida',  26),
 (cidade_seq.nextval, 'Aparecida d`Oeste',  26),
 (cidade_seq.nextval, 'Apiaí',  26),
 (cidade_seq.nextval, 'Araçariguama',  26),
 (cidade_seq.nextval, 'Araçatuba',  26),
 (cidade_seq.nextval, 'Araçoiaba da Serra',  26),
 (cidade_seq.nextval, 'Aramina',  26),
 (cidade_seq.nextval, 'Arandu',  26),
 (cidade_seq.nextval, 'Arapeí',  26),
 (cidade_seq.nextval, 'Araraquara',  26),
 (cidade_seq.nextval, 'Araras',  26),
 (cidade_seq.nextval, 'Arco-Íris',  26),
 (cidade_seq.nextval, 'Arealva',  26),
 (cidade_seq.nextval, 'Mogi das Cruzes',  26),
 (cidade_seq.nextval, 'Mogi Guaçu',  26),
 (cidade_seq.nextval, 'Moji Mirim',  26),
 (cidade_seq.nextval, 'Mombuca',  26),
 (cidade_seq.nextval, 'Monções',  26),
 (cidade_seq.nextval, 'Mongaguá',  26),
 (cidade_seq.nextval, 'Monte Alegre do Sul',  26),
 (cidade_seq.nextval, 'Monte Alto',  26),
 (cidade_seq.nextval, 'Monte Aprazível',  26),
 (cidade_seq.nextval, 'Monte Azul Paulista',  26),
 (cidade_seq.nextval, 'Monte Castelo',  26),
 (cidade_seq.nextval, 'Sertãozinho',  26),
 (cidade_seq.nextval, 'Sete Barras',  26),
 (cidade_seq.nextval, 'Severínia',  26),
 (cidade_seq.nextval, 'Silveiras',  26),
 (cidade_seq.nextval, 'Socorro',  26),
 (cidade_seq.nextval, 'Sorocaba',  26),
 (cidade_seq.nextval, 'Sud Mennucci',  26),
 (cidade_seq.nextval, 'Sumaré',  26),
 (cidade_seq.nextval, 'Suzanápolis',  26),
 (cidade_seq.nextval, 'Suzano',  26),
 (cidade_seq.nextval, 'Nossa Senhora das Dores',  25),
 (cidade_seq.nextval, 'Nossa Senhora de Lourdes',  25),
 (cidade_seq.nextval, 'Nossa Senhora do Socorro',  25),
 (cidade_seq.nextval, 'Pacatuba',  25),
 (cidade_seq.nextval, 'Pedra Mole',  25),
 (cidade_seq.nextval, 'Pedrinhas',  25),
 (cidade_seq.nextval, 'Pinhão',  25),
 (cidade_seq.nextval, 'Pirambu',  25),
 (cidade_seq.nextval, 'Esperantina',  27),
 (cidade_seq.nextval, 'Fátima',  27),
 (cidade_seq.nextval, 'Figueirópolis',  27),
 (cidade_seq.nextval, 'Filadélfia',  27),
 (cidade_seq.nextval, 'Formoso do Araguaia',  27),
 (cidade_seq.nextval, 'Fortaleza do Tabocão',  27),
 (cidade_seq.nextval, 'Goianorte',  27),
 (cidade_seq.nextval, 'Goiatins',  27),
 (cidade_seq.nextval, 'Guaraí',  27),
 (cidade_seq.nextval, 'Gurupi',  27),
 (cidade_seq.nextval, 'Ipueiras',  27),
 (cidade_seq.nextval, 'Itacajá',  27),
 (cidade_seq.nextval, 'Itaguatins',  27),
 (cidade_seq.nextval, 'Xambioá',  27);

 insert into bandeira values
 (bandeira_seq.nextval,  'Visa'),
 (bandeira_seq.nextval,  'Mastercard'),
 (bandeira_seq.nextval,  'Elo'),
 (bandeira_seq.nextval,  'American Express'),
 (bandeira_seq.nextval,  'Hipercard'),
 (bandeira_seq.nextval,  'Diners Club'),
 (bandeira_seq.nextval,  'Sorocred');

 insert into categoria values
 (categoria_seq.nextval,'Biografias'),
 (categoria_seq.nextval,'Coleções'),
 (categoria_seq.nextval,'Contos'),
 (categoria_seq.nextval,'Crítica Literária'),
 (categoria_seq.nextval,'Ficção Científica'),
 (categoria_seq.nextval,'Folclore'),
 (categoria_seq.nextval,'Genealogia'),
 (categoria_seq.nextval,'Gibis'),
 (categoria_seq.nextval,'Humor'),
 (categoria_seq.nextval,'Infantojuvenis'),
 (categoria_seq.nextval,'Jogos'),
 (categoria_seq.nextval,'Jornais'),
 (categoria_seq.nextval,'Literatura Brasileira'),
 (categoria_seq.nextval,'Literatura Estrangeira'),
 (categoria_seq.nextval,'Livros Raros'),
 (categoria_seq.nextval,'Manuscritos'),
 (categoria_seq.nextval,'Poesia'),
 (categoria_seq.nextval,'Religiao'),
 (categoria_seq.nextval,'Revistas'),
 (categoria_seq.nextval,'Outros Assuntos');
 
 insert into editora values
 (editora_seq.nextval, 'Abril'),
 (editora_seq.nextval, 'Albatroz'),
 (editora_seq.nextval, 'Alto Astral'),
 (editora_seq.nextval, 'Casa Verde'),
 (editora_seq.nextval, 'Companhia das Letras'),
 (editora_seq.nextval, 'Contexto'),
 (editora_seq.nextval, 'Intrínseca'),
 (editora_seq.nextval, 'Objetiva'),
 (editora_seq.nextval, 'Rocco'),
 (editora_seq.nextval, 'Sextante');

 insert into genero values
 (genero_seq.nextval, 'Feminino'),
 (genero_seq.nextval, 'Masculino'),
 (genero_seq.nextval, 'Não Binário');

 insert into grupo_ativacao values
 (grupo_ativacao_seq.nextval, 'Saldo em Estoque', 'Livro deu entrada no estoque');

 insert into grupo_inativacao values
 (grupo_inativacao_seq.nextval, 'Sem Estoque', 'Livro sem saldo em Estoque');

